package com.arish.shoppersclub.config;

import java.time.Duration;

import org.springframework.cache.annotation.EnableCaching;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.redis.cache.RedisCacheConfiguration;
import org.springframework.data.redis.cache.RedisCacheManager;
import org.springframework.data.redis.connection.RedisConnectionFactory;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer;
import org.springframework.data.redis.serializer.RedisSerializationContext;
import org.springframework.data.redis.serializer.StringRedisSerializer;

@Configuration // Marks this class as a source of Spring bean definitions
@EnableCaching  // Enables Spring's annotation-driven cache management (@Cacheable, @CacheEvict, etc.)
public class RedisConfig {

    // Bean for manual Redis operations (e.g., redisTemplate.opsForValue().set(...))
    @Bean
    public RedisTemplate<String, Object> redisTemplate(RedisConnectionFactory connectionFactory) {
        // Instantiate the Spring RedisTemplate object
        RedisTemplate<String, Object> template = new RedisTemplate<>();
        
        // Pass the Redis connection details (host, port, auth) supplied automatically by Spring Boot
        template.setConnectionFactory(connectionFactory);
        
        // Create a serializer that converts Java Strings to plain text bytes for Redis keys
        StringRedisSerializer stringSerializer = new StringRedisSerializer();
        
        // Use plain text string serialization for top-level keys (e.g., "seller:100")
        template.setKeySerializer(stringSerializer);
        
        // Use plain text string serialization for Redis Hash keys (field names inside a Redis Hash)
        template.setHashKeySerializer(stringSerializer);
        
        // Create a Jackson serializer to convert Java objects to/from JSON format
        GenericJackson2JsonRedisSerializer jsonSerializer = new GenericJackson2JsonRedisSerializer();
        
        // Store values as human-readable JSON instead of binary Java serialized data
        template.setValueSerializer(jsonSerializer);
        
        // Store inner values of Redis Hashes as human-readable JSON as well
        template.setHashValueSerializer(jsonSerializer);
        
        // Initialize and validate all properties configured on the template instance
        template.afterPropertiesSet();
        
        // Return the configured RedisTemplate instance to Spring's container
        return template;
    }

    // Bean that configures how @Cacheable annotations store and expire data in Redis
    @Bean
    public RedisCacheManager cacheManager(RedisConnectionFactory connectionFactory) {
        // Create the JSON serializer instance for cache values
        GenericJackson2JsonRedisSerializer jsonSerializer = new GenericJackson2JsonRedisSerializer();
        
        // Build the cache configuration starting with default settings
        RedisCacheConfiguration cacheConfig = RedisCacheConfiguration.defaultCacheConfig()
                // Set the default expiration time (TTL) for cached entries to 10 minutes
                .entryTtl(Duration.ofMinutes(10)) 
                
                // Do not create cache entries if the method returns null
                .disableCachingNullValues()
                
                // Ensure Redis keys generated by @Cacheable are formatted as plain Strings
                .serializeKeysWith(RedisSerializationContext.SerializationPair.fromSerializer(new StringRedisSerializer()))
                
                // Ensure cache values generated by @Cacheable are converted to JSON
                .serializeValuesWith(RedisSerializationContext.SerializationPair.fromSerializer(jsonSerializer));
        
        // Build and return the cache manager using the connection factory and custom configuration
        return RedisCacheManager.builder(connectionFactory)
                .cacheDefaults(cacheConfig) // Apply default rules to all caches
                .build();                   // Construct the RedisCacheManager instance
    }

}